config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root 'details#index'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
#validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
validates :password, :confirmation => true #password_confirmation attr
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 before_action :authenticate_user!
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
def index
   @details = Detail.all
 end

def show
    @detail = Detail.find(params[:id])
  end
 def new
      @detail = Detail.new
   end
   
   def create
      @detail = Detail.new(detail_params)      
      if @detail.save
         redirect_to @detail, notice: "The member #{@detail.name} has been added."
      else
         render 'new'
      end
      
   end
 

def edit
    @detail = Detail.new(detail_params)
  end
   def update
  @detail = Detail.find(params[:id])
 
  if @detail.update(detail_params)
    redirect_to @detail
  else
    render 'edit'
  end
end

   def destroy
      @detail = Detail.find(params[:id])
      @detail.destroy
      redirect_to detail_path, notice:  "The member #{@detail.name} has been removed."
   end
   
   private
      def detail_params
      params.require(:detail).permit(:name, :password)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/index.html.erb
<!DOCTYPE html>
<html>
<head>
welcome user!
</head>

</html>

app/views/details/new.html.erb
<%= render 'form' %> <%= link_to 'Back', details_path %> 

app/views/details/show.html.erb
<html>
<h1>I am in show</h1>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Form</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login as user", new_user_session_path, :class => 'navbar-link'  %>
  <%= link_to "Login as IP committee member", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>